name: oscars
description: "The 97th Academy Awards unofficial app"
# Don't forget to update PKGBUILD when changing this version
publish_to: 'none'

version: 1.3.1-1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies required by the application
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  path: 1.9.0
  url_launcher: ^6.1.14
  html: ^0.15.4
  intl: ^0.20.0
  logging: ^1.2.0
  flutter_launcher_icons: ^0.14.3
  cached_network_image: ^3.2.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.3
  share_plus: 7.2.1
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.2
  file_picker: ^8.0.5

# Dependencies only needed during development
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_distributor: ^0.0.2
  build_runner: ^2.1.4
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

# Configuration to force specific versions
dependency_overrides:
  url_launcher_linux: 3.0.6
  path: 1.9.0

# Application icons configuration
flutter_launcher_icons:
  image_path: "assets/app-icon.png"
  android: true
  ios: true
  windows:
    generate: true
  linux:
    icon_path: "linux/runner/resources/oscars.png"
  macos:
    generate: true
    image_path: "assets/app-icon.png"

# Flutter configuration
flutter:
  uses-material-design: true
  assets:
    - assets/app-icon.png
    - assets/oscars.png