name: Flatpak Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  FLATPAK_ID: com.ali3nated0.oscars

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      # Install all build dependencies first
      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y ppa:flatpak/stable
          sudo apt-get update
          sudo apt-get install -y \
            flatpak \
            flatpak-builder \
            xz-utils \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev \
            libglu1-mesa \
            imagemagick

      # Setup Flatpak first
      - name: Setup Flatpak
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08

      # Then setup Flutter and build
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'

      - name: Build Flutter App
        run: |
          flutter config --enable-linux-desktop
          flutter doctor -v
          flutter pub get
          
          # Build Flutter app
          flutter build linux --release
          
          # Prepare icons - resize to 512x512 if needed
          mkdir -p icons
          convert assets/oscars.png -resize 512x512 icons/com.ali3nated0.oscars.png
          
          # Copy files to build directory
          rm -rf flatpak-build
          mkdir -p flatpak-build
          cp -r build/linux/x64/release/bundle/* flatpak-build/
          cp icons/com.ali3nated0.oscars.png flatpak-build/
          
          # Create desktop entry with correct icon name
          cat > flatpak-build/com.ali3nated0.oscars.desktop << EOF
          [Desktop Entry]
          Name=Oscars
          Exec=oscars
          Icon=com.ali3nated0.oscars
          Type=Application
          Categories=Entertainment;
          EOF

      - name: Create Flatpak Manifest
        run: |
          cat > com.ali3nated0.oscars.yml << EOF
          app-id: com.ali3nated0.oscars
          runtime: org.freedesktop.Platform
          runtime-version: '23.08'
          sdk: org.freedesktop.Sdk
          command: oscars
          finish-args:
            - --share=ipc
            - --socket=fallback-x11
            - --socket=wayland
            - --device=dri
            - --filesystem=home
            # Add share/system for glib
            - --env=GIO_EXTRA_MODULES=/app/lib/gio/modules
          modules:
            - name: oscars
              buildsystem: simple
              build-commands:
                - install -Dm755 oscars /app/bin/oscars
                - install -d /app/lib
                - cp -r lib/* /app/lib/
                - install -Dm644 com.ali3nated0.oscars.desktop /app/share/applications/${FLATPAK_ID}.desktop
                - install -Dm644 com.ali3nated0.oscars.png /app/share/icons/hicolor/512x512/apps/${FLATPAK_ID}.png
              sources:
                - type: dir
                  path: flatpak-build
              # Add glib dependency
              add-extensions:
                org.freedesktop.Platform.GL:
                  version: '23.08'
                  directory: lib/GL
                  subdirectories: true
                  no-autodownload: true
                  autodelete: false
                org.freedesktop.Platform.Timezones:
                  version: '23.08'
                  directory: share/zoneinfo
          EOF

      - name: Build Flatpak Package
        run: |
          echo "Building Flatpak..."
          flatpak-builder --force-clean --repo=repo build-flatpak com.ali3nated0.oscars.yml
          echo "Creating bundle..."
          flatpak build-bundle repo oscars_${{ inputs.version }}.flatpak $FLATPAK_ID

      - name: Upload Flatpak Package
        uses: actions/upload-artifact@v4
        with:
          name: oscars-Flatpak
          path: oscars_${{ inputs.version }}.flatpak
