name: Linux Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string
        default: '1.0.0-1'
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Version number'

env:
  FLUTTER_VERSION: '3.19.3'

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            clang \
            pkg-config \
            libgtk-3-dev \
            libsecret-1-dev \
            liblzma-dev \
            libglib2.0-dev \
            fuse \
            appstream

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Build App
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release

      # AppImage build
      - name: Create AppImage Structure
        run: |
          mkdir -p AppDir
          cp -r build/linux/x64/release/bundle/* AppDir/
          cp assets/oscars.png AppDir/oscars.png
          
          cat > AppDir/AppRun << 'EOF'
          #!/bin/sh
          cd "$(dirname "$0")"
          exec ./oscars "$@"
          EOF
          chmod +x AppDir/AppRun
          
          cat > AppDir/oscars.desktop << EOF
          [Desktop Entry]
          Name=Oscars
          Exec=oscars
          Icon=oscars
          Type=Application
          Categories=Utility;
          EOF

      - name: Get AppImage Tool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Build AppImage
        run: |
          ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir oscars_${{ inputs.version || github.event.inputs.version }}.AppImage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: oscars-AppImage
          path: oscars_${{ inputs.version || github.event.inputs.version }}.AppImage

      # DEB build
      - name: Build DEB Package
        run: |
          PKGDIR=oscars_${{ inputs.version || github.event.inputs.version }}_amd64
          
          # Create directory structure
          mkdir -p $PKGDIR/DEBIAN
          mkdir -p $PKGDIR/usr/bin
          mkdir -p $PKGDIR/usr/lib/oscars
          mkdir -p $PKGDIR/usr/share/applications
          mkdir -p $PKGDIR/usr/share/icons/hicolor/256x256/apps
          
          # Copy files
          cp -r build/linux/x64/release/bundle/* $PKGDIR/usr/lib/oscars/
          cp assets/oscars.png $PKGDIR/usr/share/icons/hicolor/256x256/apps/oscars.png
          
          # Create launcher
          cat > $PKGDIR/usr/bin/oscars << 'EOF'
          #!/bin/sh
          cd /usr/lib/oscars
          exec ./oscars "$@"
          EOF
          chmod 755 $PKGDIR/usr/bin/oscars

          # Create control file
          cat > $PKGDIR/DEBIAN/control << EOF
          Package: oscars
          Version: ${{ inputs.version || github.event.inputs.version }}
          Architecture: amd64
          Maintainer: ALi3naTEd0 <your@email.com>
          Depends: libgtk-3-0, libsecret-1-0
          Section: utils
          Priority: optional
          Description: The 97th Academy Awards app
           A Flutter application for exploring Oscar nominated movies.
          EOF
          
          # Create desktop entry
          cat > $PKGDIR/usr/share/applications/oscars.desktop << EOF
          [Desktop Entry]
          Name=Oscars
          Exec=/usr/bin/oscars
          Icon=oscars
          Type=Application
          Categories=Utility;
          EOF
          chmod 644 $PKGDIR/usr/share/applications/oscars.desktop

          # Set permissions
          chmod 755 -R $PKGDIR/usr/lib/oscars
          
          # Build DEB
          dpkg-deb --build $PKGDIR

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: oscars-DEB
          path: oscars_${{ inputs.version || github.event.inputs.version }}_amd64.deb

      # RPM build
      - name: Build RPM Package
        run: |
          # Install alien for DEB to RPM conversion
          sudo apt-get install -y alien rpm

          # Convert DEB to RPM and rename to match convention
          sudo alien --scripts --to-rpm oscars_${{ inputs.version || github.event.inputs.version }}_amd64.deb
          mv oscars-*.rpm oscars_${{ inputs.version || github.event.inputs.version }}_x86_64.rpm

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: oscars-RPM
          path: oscars_${{ inputs.version || github.event.inputs.version }}_x86_64.rpm

      - name: Update PKGBUILD version
        run: |
          sed -i "s/pkgver=.*/pkgver=${{ inputs.version || github.event.inputs.version }}/" PKGBUILD
