name: macOS Build

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Build macOS
        run: |
          flutter config --enable-macos-desktop
          flutter pub get
          flutter build macos --release

      - name: Create DMG
        run: |
          brew install create-dmg
          
          APP_NAME="oscars"
          APP_PATH="build/macos/Build/Products/Release/oscars.app"
          DMG_PATH="$APP_NAME.dmg"
          
          create-dmg \
            --volname "$APP_NAME" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "$APP_NAME.app" 200 190 \
            --hide-extension "$APP_NAME.app" \
            --app-drop-link 600 185 \
            "$DMG_PATH" \
            "$APP_PATH"

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: oscars-macos
          path: oscars.dmg
