name: Matrix Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        target: [android, windows, linux, macos]
        include:
          - target: android
            os: ubuntu-latest
            build-args: apk
            
          - target: windows
            os: windows-latest
            build-args: windows
            
          - target: linux
            os: ubuntu-latest
            build-args: linux
            
          - target: macos
            os: macos-latest
            build-args: macos
            
    steps:
      - uses: actions/checkout@v4
      
      - if: matrix.target == 'linux'
        name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true
          
      - name: Build ${{ matrix.target }}
        run: |
          flutter config --enable-${{ matrix.target }}-desktop
          flutter build ${{ matrix.build-args }} --debug
