name: Matrix Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "1.0.0-1"
      platforms:
        description: "Platforms to build"
        required: true
        type: choice
        options:
          - all
          - android
          - linux
          - windows
          - macos

jobs:
  android:
    if: ${{ inputs.platforms == 'all' || inputs.platforms == 'android' }}
    uses: ALi3naTEd0/Oscars/.github/workflows/android.yml@main
    secrets: inherit
    with:
      version: ${{ inputs.version }}

  linux:
    if: ${{ inputs.platforms == 'all' || inputs.platforms == 'linux' }}
    uses: ALi3naTEd0/Oscars/.github/workflows/linux.yml@main
    secrets: inherit
    with:
      version: ${{ inputs.version }}

  windows:
    if: ${{ inputs.platforms == 'all' || inputs.platforms == 'windows' }}
    uses: ALi3naTEd0/Oscars/.github/workflows/windows.yml@main
    secrets: inherit
    with:
      version: ${{ inputs.version }}

  macos:
    if: ${{ inputs.platforms == 'all' || inputs.platforms == 'macos' }}
    uses: ALi3naTEd0/Oscars/.github/workflows/macos.yml@main
    secrets: inherit
    with:
      version: ${{ inputs.version }}
