name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (This will be used in ALL platform builds)'
        required: true
        default: '1.0.0-1'

permissions:
  contents: write
  actions: write

jobs:
  trigger-builds:
    strategy:
      matrix:
        platform: [android, linux, windows, macos]
      fail-fast: false
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Trigger ${{ matrix.platform }} build
        id: trigger
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflow = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '${{ matrix.platform }}.yml',
              ref: context.ref,
              inputs: {
                version: '${{ github.event.inputs.version }}'
              }
            });
            console.log(`Triggered ${workflow.status}`);
            return workflow.status;

      - name: Wait for build
        run: sleep 30  # Give time for builds to start

  # Wait for all artifacts and create release
  create-release:
    needs: trigger-builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Wait for artifacts
        run: |
          echo "Waiting for builds to complete..."
          sleep 300  # Wait 5 minutes for builds to finish

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: oscars-*
          path: dist
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          files: |
            dist/**/*
