name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "1.0.0-1"

jobs:
  android:
    uses: ./.github/workflows/android.yml
    with:
      version: ${{ github.event.inputs.version }}

  linux:
    uses: ./.github/workflows/linux.yml
    with:
      version: ${{ github.event.inputs.version }}

  windows:
    uses: ./.github/workflows/windows.yml
    with:
      version: ${{ github.event.inputs.version }}

  macos:
    uses: ./.github/workflows/macos.yml
    with:
      version: ${{ github.event.inputs.version }}

  release:
    needs: [android, linux, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - run: ls -R dist/
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          files: dist/**/*