name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "1.0.0-1"

jobs:
  compile:
    strategy:
      matrix:
        workflow: [android, linux, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ matrix.workflow }}.yml/dispatches \
            -d '{"ref":"main","inputs":{"version":"${{ github.event.inputs.version }}"}}'

  create-release:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Wait for builds
        run: sleep 180  # Wait 3 minutes for builds to complete
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: List artifacts
        run: ls -R artifacts/
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          files: artifacts/**/*
