name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "1.0.0-1"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            script: |
              flutter build apk --release
              mv build/app/outputs/flutter-apk/app-release.apk oscars-${{ github.event.inputs.version }}.apk
          - os: ubuntu-latest
            script: |
              flutter build linux --release
              # Build AppImage, DEB, RPM
          - os: windows-latest
            script: |
              flutter build windows --release
              # Build portable and installer
          - os: macos-latest
            script: |
              flutter build macos --release
              # Build DMG
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
      - run: ${{ matrix.script }}
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            *.apk
            *.AppImage
            *.deb
            *.rpm
            *.zip
            *.exe
            *.dmg

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          draft: true
          files: artifacts/**/*