name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "1.0.0-1"

jobs:
  compile:
    strategy:
      matrix:
        platform: [android, linux, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Run workflow
        run: |
          gh workflow run ${{ matrix.platform }}.yml -f version=${{ github.event.inputs.version }}
          sleep 30
        env:
          GH_TOKEN: ${{ github.token }}

  release:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - run: ls -R dist/
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          files: dist/**/*