name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "1.0.0-1"

jobs:
  compile:
    strategy:
      matrix:
        workflow: [android, linux, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        run: |
          gh workflow run ${{ matrix.workflow }}.yml --ref main -f version=${{ github.event.inputs.version }}
        env:
          GH_TOKEN: ${{ github.token }}

  create-release:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: sleep 60
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: ls -R artifacts/
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          files: artifacts/**/*
